# Generated by Django 3.1.7 on 2021-03-26 15:43

import apps.user_profile.services
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProfileModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, validators=[django.core.validators.RegexValidator('^[a-zA-ZА-яёЁґҐіІїЇєЄ]{2,20}$', 'Only alpha, min 2 max 20 ch')])),
                ('surname', models.CharField(max_length=20, validators=[django.core.validators.RegexValidator('^[a-zA-ZА-яёЁґҐіІїЇєЄ]{2,20}$', 'Only alpha, min 2 max 20 ch')])),
                ('age', models.IntegerField(validators=[django.core.validators.MinValueValidator(10), django.core.validators.MaxValueValidator(130)])),
                ('avatar', models.ImageField(upload_to=apps.user_profile.services.avatar_upload)),
            ],
            options={
                'db_table': 'profile',
            },
        ),
    ]
